GET http://localhost:3000/projects
###

POST http://localhost:3000/projects
Content-Type: application/json

{
    "name": "Social Media Platform" ,
    "link" : "https://final-capstone-frontend-y54c.onrender.com/",
    "description" : "full MERN stack social platform with full CRUD operations" 
}
###

DELETE http://localhost:3000/projects/66752b1b732566964de23f3a
###