GET http://localhost:3000/projects
###

POST http://localhost:3000/projects
Content-Type: application/json

{
    "name": "Login/signup form" ,
    "link" : "https://login-signup-ibyp.onrender.com/",
    "description" : "React front end log in form" 
}
###

DELETE http://localhost:3000/projects/667b3e824e26b65becbe2ef9
###